services:
  myrient-search:
    image: ghcr.io/alexankitty/myrient-search-engine:latest
    ports:
      - "8062:8062"
    environment:
      - PORT=8062
      - BIND_ADDRESS=0.0.0.0
      - FORCE_FILE_REBUILD=0
      - DEBUG=0
      - NODE_ENV=production
      - MAX_JOB_QUEUE=1000
      - MAX_FETCH_JOBS=1000
      - INSTANCE_NAME=Myrient
      - EMULATOR_ENABLED=true
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=myrient
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=this-is-a-secure-db-password
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    volumes:
      - ./data:/usr/src/app/data
    depends_on:
      - postgres
      - elasticsearch
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:8.17.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    deploy: # Remove if you have a lot of free memory
      resources:
        limits:
          memory: 512M
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: this-is-a-secure-db-password
      POSTGRES_DB: myrient
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  elasticsearch_data:
  postgres_data: